import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Radix App",
  description: "Generated by create next app with Radix UI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body>
        <Theme appearance="light" accentColor="green" grayColor="sage">
          {children}
        </Theme>
      </body>
    </html>
  );
}
